### ISSUE TITLE
Hard-coded endpoint

### ISSUE THREAD

**Issue by zrendy** [RFCE2209-Baratheon/Front-End-Capstone#72]
**Hardcoded endpoint**
This endpoint has a hard-coded parameter, this will increase the helpful count of only the review with id of 1275306
https://github.com/RFCE2209-Baratheon/Front-End-Capstone/blob/b671387ab9438d6837c9b4cfb62a582459007a3b/server/index.js#L268-L277

**Comment by sterno2510** [comment]
This has been fixed!
