### ISSUE TITLE
Accessibility form-control

### ISSUE THREAD

**Issue by shethinksnyc** [RFCE2209-Baratheon/Front-End-Capstone#75]
https://github.com/RFCE2209-Baratheon/Front-End-Capstone/blob/b671387ab9438d6837c9b4cfb62a582459007a3b/client/src/components/QA/AddAnswerModal.jsx#L55-L62

Really organized code, very easy to walk through. Consider using the label tag to improve accessibility. 

resources: https://www.w3.org/WAI/tutorials/forms/labels/
https://webaim.org/techniques/forms/controls
https://stackoverflow.com/questions/12890882/label-vs-span-html

**Comment by vamman311** [comment]
I believe this is the proper implementation for labels, please review.

![image](https://user-images.githubusercontent.com/24787921/198846936-f4b6e824-72f9-4792-a1c3-c98af2b210ca.png)

**Comment by vamman311** [comment]
I recently noticed an error with the ending tags.  They have also been corrected.  Closing this issue now.
