### ISSUE TITLE
UI - User experience

### ISSUE THREAD

**Issue by shethinksnyc** [RFCE2209-Baratheon/Front-End-Capstone#76]
![ui review](https://user-images.githubusercontent.com/78012387/198845459-b96e591a-7908-4cfb-9300-4712169711b8.png)

I really appreciate the typography choice and spacing between characters allowing for an easy read. Consider spacing divs (vertically )a bit more to make texts from questions and answers feel less congested. 

Resources: https://uxplanet.org/spacing-guide-for-designers-5bd140afe52a
https://ishadeed.com/article/spacing-in-css/

**Comment by vamman311** [comment]
![image](https://user-images.githubusercontent.com/24787921/198846747-c1b09591-56bd-44fa-8517-29d127ddcdb0.png)

Here's the fix thanks for the advice looks much better now
